version: '3'
services:
  api:
    image: nodejs-app
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_URI: db
    networks:
      - backend
    ports:
      - "3000:3000"
    depends_on:
      - db

  web-cli:
    image: nodejs-cli
    build:
      context: ./
      dockerfile: Dockerfile.curl
    networks:
      - backend
    command: sh
    depends_on:
      - api

  db:
    image: nodejs-mysql
    build:
      context: ./
      dockerfile: Dockerfile.db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: WST6wPB9Tweehnne
    networks:
      - backend

networks:
  backend:
    driver: bridge
