version: '3'
services:
  api:
    image: nodejs-app
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"

  web-cli:
    image: nodejs-app
    networks:
      - backend
    command: sh
    depends_on:
      - api
networks:
  backend:
    driver: bridge
