steps:
  - name: ":docker: Build"
    soft_fail:
      - exit_status: 1
    plugins:
      - docker-compose#v3.1.0:
          build: .

  - wait

  - name: ":node: Pre-Test(Lint)"
    soft_fail:
      - exit_status: 1
    plugins:
      - docker-compose#v3.1.0:
          run: api
          command: ["npm", "run", "pre-test"]

  - name: ":node: Test"
    plugins:
      - docker-compose#v3.1.0:
          run:
            - web-cli
          command: ["npm", "run", "test"]